# Generated by Django 5.1.3 on 2024-11-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0003_people_100_cpejdzs'),
    ]

    operations = [
        migrations.CreateModel(
            name='people-100_QL7kyta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=255)),
                ('User Id', models.CharField(max_length=255)),
                ('First Name', models.CharField(max_length=255)),
                ('Last Name', models.CharField(max_length=255)),
                ('Sex', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Date of birth', models.CharField(max_length=255)),
                ('Job Title', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='people-100_cpejDZS',
        ),
    ]
