# Generated by Django 5.1.3 on 2024-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0006_customers_100'),
    ]

    operations = [
        migrations.CreateModel(
            name='organizationit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Index', models.CharField(max_length=255)),
                ('Organization Id', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Website', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=255)),
                ('Founded', models.CharField(max_length=255)),
                ('Industry', models.CharField(max_length=255)),
                ('Number of employees', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='customers-100',
        ),
        migrations.DeleteModel(
            name='people-100_HHHmiTD',
        ),
    ]
