# Generated by Django 5.1.3 on 2024-11-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0007_organizationit_delete_customers_100_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Industry', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='organizationit',
        ),
    ]
