# Generated by Django 5.1.3 on 2024-11-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0009_size_delete_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Continent', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='size',
        ),
    ]
