# Generated by Django 5.1.3 on 2024-11-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0010_continent_delete_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Code', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='continent',
        ),
    ]
