# Generated by Django 5.1.3 on 2024-11-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0012_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agreement', models.CharField(max_length=255)),
            ],
        ),
    ]
