# Generated by Django 5.1.3 on 2024-11-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0014_importance'),
    ]

    operations = [
        migrations.CreateModel(
            name='importance_HpwUY6e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importance', models.CharField(max_length=255)),
            ],
        ),
    ]
