# Generated by Django 5.1.3 on 2024-11-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0022_size_im2h3mb_delete_age_delete_age_rdgdqzh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='size_eNmqNsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=255)),
                ('Abbreviated Size', models.CharField(max_length=255)),
            ],
        ),
    ]
