# Generated by Django 5.1.3 on 2024-11-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0024_comparison'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comparison',
            new_name='comparison_Rubg6fV',
        ),
        migrations.DeleteModel(
            name='size_eNmqNsv',
        ),
        migrations.DeleteModel(
            name='size_iM2h3Mb',
        ),
    ]
