# Generated by Django 5.1.3 on 2024-11-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0028_comparison_r9jxgzc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comparison_R9JXgzC',
            new_name='comparison_Y4ReWN9',
        ),
        migrations.DeleteModel(
            name='comparison_1GjS8tg',
        ),
        migrations.DeleteModel(
            name='comparison_JM1PtfN',
        ),
        migrations.DeleteModel(
            name='comparison_Rubg6fV',
        ),
    ]
