# Generated by Django 5.1.3 on 2024-11-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0029_rename_comparison_r9jxgzc_comparison_y4rewn9_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comparison_Y4ReWN9',
            new_name='comparison_77bzXqP',
        ),
    ]
