# Generated by Django 5.1.3 on 2024-11-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0030_rename_comparison_y4rewn9_comparison_77bzxqp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comparison_77bzXqP',
            new_name='comparison_uZFlSTa',
        ),
    ]
