# Generated by Django 5.1.3 on 2024-11-27 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseLoader', '0036_comparison_fyoto6h'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comparison_xKeBdHg',
            new_name='comparison_NrvihSW',
        ),
        migrations.DeleteModel(
            name='comparison_DQRJ1Vm',
        ),
        migrations.DeleteModel(
            name='comparison_FyOTo6H',
        ),
        migrations.DeleteModel(
            name='comparison_Ol4Hs17',
        ),
        migrations.DeleteModel(
            name='comparison_uZFlSTa',
        ),
        migrations.DeleteModel(
            name='comparison_XciiYB3',
        ),
    ]
